# System
alias ls='ls --color=auto'
alias ll='ls -la'
alias la='ls -a'
alias cat='bat'
alias sysf='fastfetch --logo XeroArch'
alias cls='clear'
alias clsh='cd && clear'
alias rmpkg='sudo rm -rf /var/cache/pacman/pkg/* && sudo rm -rf /home/joaob/.cache/yay/*'
alias pwoff='sudo systemctl poweroff'
alias rebootsys='sudo systemctl reboot'
alias suspend='sudo systemctl suspend'
alias light-low='xrandr --output HDMI-A-0 --brightness 0.3'
alias light-default='xrandr --output HDMI-A-0 --brightness 1'

# Git
alias ginit='git init'
alias gbranch='git branch'
alias gcheckb='git checkout'
alias gdelb='git branch -d'
alias gdelbf='git branch -D'
alias gadda='git add .'
alias gadd='git add'
alias gcommit='git commit -m'
alias gpush='git push'
alias gpusho='git push origin'
alias gpushom='git push origin main'
alias greseth='git reset --hard'
alias gresets='git reset --soft'
alias gremotev='git remote -v'
alias gremotea='git remote add'
alias gremoteao='git remote add origin'
alias gremoterm='git remote remove'
alias gmremotermo='git remote remove origin'
alias glog='git log'
alias gstat='git status'
alias gpusham='git add . && git commit -m "." && git push origin main'

# Kitty
alias icat='kitten icat'
