# ~/.tmux.conf

# Desabilita barra de status
set -g status off

# Prefixo para Ctrl+a
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# Habilitar cores
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",alacritty:Tc"

# --- Atalhos de Abas (Estilo Kitty) ---
bind t new-window             # Nova aba
bind q kill-window            # Fechar aba
bind [ previous-window        # Aba anterior[cite: 3]
bind ] next-window            # Próxima aba[cite: 3]
bind . swap-window -t +1      # Mover aba para frente[cite: 3]
bind , swap-window -t -1      # Mover aba para trás[cite: 3]

# Atalhos para tabs específicas (1 a 9)
bind 1 select-window -t 1
bind 2 select-window -t 2
bind 3 select-window -t 3
bind 4 select-window -t 4
bind 5 select-window -t 5
bind 6 select-window -t 6
bind 7 select-window -t 7
bind 8 select-window -t 8
bind 9 select-window -t 9

# --- Gerenciamento de Painéis e Layouts ---
bind w kill-pane              # Fechar painel
bind l next-layout            # Próximo layout
bind r resize-pane            # Modo redimensionamento
bind | split-window -h        # Painel horizontal[cite: 3]
bind - split-window -v        # Painel vertical[cite: 3]

# --- Navegação (Painéis) ---
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# --- Scrollback ---
bind h copy-mode              # Entra no modo de visualização

# --- Configurações Gerais ---
set -g mouse on
