background = rgb(000000)
base = rgb(171717)
text = rgb(e5e5e5)
alternate_base = rgb(262626)
bright_text = rgb(ffffff)
accent = rgb(737373)
accent_secondary = rgb(a3a3a3)
font_family = Wigrum Regular
font_family_monospace = JetBrains Mono
font_size = 12
small_font_size = 10
icon_theme = bloom-dark
