#! /bin/sh

feh --bg-scale ~/Images/wallpapers/wallpaper.png

picom -b --config ~/.config/picom/picom.conf

xrandr --output HDMI-A-0 --scale 1.4x1.4 --brightness 0.4

killall polybar && killall sxhkd
polybar bar1 &
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6

bspc config pointer_follows_focus true
bspc config border_width         4
bspc config focused_border_color "#5e9a99"
bspc config top_padding          20
bspc config window_gap           3

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Emacs state=floating center=true rectangle=920x700+0+0
bspc rule -a gnome-calculator state=floating rectangle=700x600+1200+200
bspc rule -a Qalculate-gtk state=floating rectangle=700x600+1100+200
bspc rule -a kitty state=floating center=true rectangle=820x600+0+0
