#! /bin/sh

xsetwacom set $(xsetwacom --list devices | grep -i "eraser" | grep -oP 'id: \K\d+') Rotate half
xsetwacom set $(xsetwacom --list devices | grep -i "eraser" | grep -oP 'id: \K\d+') PressureCurve 0 0 30 70

feh --bg-scale ~/Images/wallpapers/wallpaper.png

xrandr --output HDMI-A-0 --scale 1.5x1.5 --brightness 0.6

killall polybar && killall sxhkd
polybar bar1 &
pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr &

bspc monitor -d 1 2 3 4 5 6

bspc config pointer_follows_focus true
bspc config border_width         1
bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedaback_color "#6272a4"
bspc config top_padding          20
bspc config window_gap           3
bspc config focus_follows_pointer true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Qalculate-gtk state=floating rectangle=700x600+1225+200
bspc rule -a kitty state=floating center=true rectangle=1125x730+0+0
# bspc rule -a Emacs state=floating center=true rectangle=1145x760+0+0
bspc rule -a pavucontrol state=floating center=true
bspc rule -a Thunar state=floating center=true rectangle=1050x600+0+0
bspc rule -a Gigolo state=floating center=true rectangle=700x450+0+0
