#! /bin/sh

xsetwacom set 15 Rotate half
xsetwacom set 15 PressureCurve 0 0 30 70

feh --bg-scale ~/Images/wallpapers/wallpaper.png

picom -b --config ~/.config/picom/picom.conf

xrandr --output HDMI-A-0 --scale 1.5x1.5 --brightness 0.5

killall polybar && killall sxhkd
polybar bar1 &
pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr &

bspc monitor -d 1 2 3 4 5 6

bspc config pointer_follows_focus true
bspc config border_width         4
bspc config focused_border_color "#5e9a99"
bspc config top_padding          20
bspc config window_gap           3

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Qalculate-gtk state=floating rectangle=700x600+1225+200
bspc rule -a kitty state=floating center=true rectangle=820x600+0+0
bspc rule -a pavucontrol state=floating center=true
bspc rule -a Thunar state=floating center=true rectangle=1050x600+0+0
