# ~/.config/alacritty/alacritty.toml

[terminal]
# Inicia o tmux automaticamente ao abrir
shell = { program = "/usr/bin/tmux", args = ["new-session", "-A", "-s", "main"] }

[window]
padding = { x = 0, y = 0 }
opacity = 1.0

[font]
size = 9.0
normal = { family = "0xProto Nerd Font", style = "Regular" }
bold = { family = "0xProto Nerd Font", style = "Bold" }
italic = { family = "0xProto Nerd Font", style = "Italic" }

[cursor]
style = { shape = "Beam", blinking = "On" }
unfocused_hollow = true

[scrolling]
history = 2000
multiplier = 5

[mouse]
hide_when_typing = true

[colors.primary]
foreground = "#171421"
background = "#FFFFFF"

[colors.selection]
text = "#FFFFFF"
background = "#000000"

[colors.normal]
black =   "#171421"
red =     "#C01C28"
green =   "#26A269"
yellow =  "#A2734C"
blue =    "#12488B"
magenta = "#A347BA"
cyan =    "#2AA1B3"
white =   "#D0CFCC"

[colors.bright]
black =   "#5E5C64"
red =     "#F66151"
green =   "#33D17A"
yellow =  "#E9AD0C"
blue =    "#2A7BDE"
magenta = "#C061CB"
cyan =    "#33C7DE"
white =   "#ffffff"
